a = input('Digite algo: ')
print ('O tipo primitivo deste valor é', type(a))
print ('É apenas espaço?', a.isspace())
print ('É numérico?', a.isnumeric())
print ('É alfabético?', a.isalpha())
print ('É alfanumérico?', a.isalnum())
print ('Tá em maiúsculas?', a.isupper())
print ('Tá em minúsculas?', a.islower())
print ('Está capitalizada?', a.istitle())
